# Generated by Django 4.1.5 on 2023-01-21 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teasers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title'], name='index_category_title'),
        ),
        migrations.AddIndex(
            model_name='teaser',
            index=models.Index(fields=['title'], name='index_teaser_title'),
        ),
        migrations.AddIndex(
            model_name='teaser',
            index=models.Index(fields=['status'], name='index_teaser_status'),
        ),
        migrations.AddConstraint(
            model_name='teaser',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='unique_teaser'),
        ),
    ]
