name: Test-api workflow

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.1-alpine
        env:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: | 
        pip install poetry==1.3.2
        poetry install

    - name: Test with pytest
      run: |
        poetry run python manage.py migrate
        poetry run pytest
      env:
        POSTGRES_DB: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        DJANGO_SECRET_KEY: ${{ github.sha }}
        DJANGO_DEBUG: True
        DJANGO_LOG_LEVEL: DEBUG
